In [2]:
import pandas as pd
import numpy as np

In [3]:
np.random.seed(101) #passar um seed para setar numeros aleatorios iguais em qualquer computador

In [6]:
df = pd.DataFrame(np.random.randn(5,4), index = 'A B C D E'.split(), columns='W X Y Z'.split()) #cria uma "planilha" tendo linhas e colunas e chamando a funcao random para popular a planilha

In [7]:
df #printa todas as colunas

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [9]:
df['W'] #printa a coluna W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [10]:
type(df['W']) #tipo da coluna W

pandas.core.series.Series

In [13]:
type(df) #tipo do df

pandas.core.frame.DataFrame

In [14]:
df[['W', 'Z']] #escolhe as colunas que quer selecionar

          W         Z
A  0.302665 -1.159119
B -0.134841  0.184502
C  0.807706  0.329646
D -0.497104  0.484752
E -0.116773  1.996652

In [15]:
df.W #outra maneira de chamar a coluna W

A    0.302665
B   -0.134841
C    0.807706
D   -0.497104
E   -0.116773
Name: W, dtype: float64

In [16]:
df['new'] = df['W'] + df['X'] #criar colunas associando como se elas ja existissem

In [17]:
df

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

In [18]:
df.drop('new', axis = 1) #funcao para apagar uma coluna

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [19]:
df #mostrando q o drop foi temporario, n alterou no df o drop de new

          W         X         Y         Z       new
A  0.302665  1.693723 -1.706086 -1.159119  1.996388
B -0.134841  0.390528  0.166905  0.184502  0.255687
C  0.807706  0.072960  0.638787  0.329646  0.880666
D -0.497104 -0.754070 -0.943406  0.484752 -1.251174
E -0.116773  1.901755  0.238127  1.996652  1.784981

df = df.drop('new', axis = 1) #agr new sera de fato apagado

In [20]:
df.drop('new', axis =1, inplace = True) #assim eh outra maneira de apagar a coluna new de df

In [21]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [22]:
df.loc['A','W'] #localizacao de elementos por indice

np.float64(0.3026654485851825)

In [23]:
df.loc['A'] #so printa a linha A

W    0.302665
X    1.693723
Y   -1.706086
Z   -1.159119
Name: A, dtype: float64

In [24]:
df.loc[['A', 'B'], ['X', 'Y', 'Z']] #lista de valores para encontrar as colunas x,y,z pelas linhas A e B

          X         Y         Z
A  1.693723 -1.706086 -1.159119
B  0.390528  0.166905  0.184502

In [36]:
df.iloc[2:4, 1:3] #outra forma de encontrando valores baseados em indice, aqui o panda vai selecionar dados utilizando notacao de numpy(indeces)

         X         Y
C  0.07296  0.638787
D -0.75407 -0.943406