In [2]:
import pandas as pd
import numpy as np

In [3]:
from numpy.random import randn
np.random.seed(101)

In [ ]:
df = pd.DataFrame(randn(5,4), index='A B C D E'.split(), columns='W X Y Z'.split()) #criando um dataframe com 5 linhas e 4 colunas, usando o metodo randn para gerar numeros aleatorios seguindo uma distribuicao normal, usando o metodo seed para garantir que os numeros aleatorios sejam os mesmos toda vez que o codigo for executado, usando o metodo DataFrame para criar o dataframe e passando os parametros de numeros aleatorios, index e columns

In [6]:
df

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [7]:
df > 0 #printa quais sao os numeros da tabela que sao maiores que 0

       W      X      Y      Z
A   True   True  False  False
B  False   True   True   True
C   True   True   True   True
D  False  False  False   True
E  False   True   True   True

In [8]:
bol = df > 0 # cria variavel bol para receber teste condicional

In [9]:
df[bol] #metodo se comporta igual numpy, printa todos aqueles que sao maior que zero e nan pros q nao

          W         X         Y         Z
A  0.302665  1.693723       NaN       NaN
B       NaN  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D       NaN       NaN       NaN  0.484752
E       NaN  1.901755  0.238127  1.996652

In [10]:
df[df['W']>0] #printa todas as linhas que contem os numeros q na coluna W sao maiores que zero

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
C  0.807706  0.072960  0.638787  0.329646

In [12]:
df[df['W']>0]['Y'] #printa todas as linhas que contem os numeros q na coluna W sao maiores que zero mas limitando a coluna Y

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [14]:
bol = df['W']>0 #mesma coisa que o de cima so q mais verboso
df2 = df[bol]
df2['Y']

A   -1.706086
C    0.638787
Name: Y, dtype: float64

In [16]:
df[(df['W']>0) & (df['Y']>1)] #faz condicionais and mas utilizando o & se n da erro, mas retorna as linhas de W e Y q sao maiores q 0 e 1

Empty DataFrame
Columns: [W, X, Y, Z]
Index: []

In [17]:
df.reset_index() #reseta os indeces e trasforma o indece antigo em coluna

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [18]:
df #como n setei q df recebe aquela funcao de resetar indece, ele n vai manter a motificacao

          W         X         Y         Z
A  0.302665  1.693723 -1.706086 -1.159119
B -0.134841  0.390528  0.166905  0.184502
C  0.807706  0.072960  0.638787  0.329646
D -0.497104 -0.754070 -0.943406  0.484752
E -0.116773  1.901755  0.238127  1.996652

In [19]:
df.reset_index(inplace=True) #pra manter coloca o inplace pra manter as modificacoes

In [20]:
df

  index         W         X         Y         Z
0     A  0.302665  1.693723 -1.706086 -1.159119
1     B -0.134841  0.390528  0.166905  0.184502
2     C  0.807706  0.072960  0.638787  0.329646
3     D -0.497104 -0.754070 -0.943406  0.484752
4     E -0.116773  1.901755  0.238127  1.996652

In [21]:
col = 'RS RJ SP AM SC'.split()

In [22]:
col

['RS', 'RJ', 'SP', 'AM', 'SC']

In [23]:
df['Estado'] = col

In [24]:
df

  index         W         X         Y         Z Estado
0     A  0.302665  1.693723 -1.706086 -1.159119     RS
1     B -0.134841  0.390528  0.166905  0.184502     RJ
2     C  0.807706  0.072960  0.638787  0.329646     SP
3     D -0.497104 -0.754070 -0.943406  0.484752     AM
4     E -0.116773  1.901755  0.238127  1.996652     SC

In [25]:
df.set_index('Estado') #toda a criacao da col estados foi feita para seta-la como indice na coluna df

       index         W         X         Y         Z
Estado
RS         A  0.302665  1.693723 -1.706086 -1.159119
RJ         B -0.134841  0.390528  0.166905  0.184502
SP         C  0.807706  0.072960  0.638787  0.329646
AM         D -0.497104 -0.754070 -0.943406  0.484752
SC         E -0.116773  1.901755  0.238127  1.996652

In [26]:
df #n foi feita a alteracao permanente por isso colocamos o inplace

  index         W         X         Y         Z Estado
0     A  0.302665  1.693723 -1.706086 -1.159119     RS
1     B -0.134841  0.390528  0.166905  0.184502     RJ
2     C  0.807706  0.072960  0.638787  0.329646     SP
3     D -0.497104 -0.754070 -0.943406  0.484752     AM
4     E -0.116773  1.901755  0.238127  1.996652     SC

In [27]:
df.set_index('Estado', inplace=True)

In [28]:
df

       index         W         X         Y         Z
Estado
RS         A  0.302665  1.693723 -1.706086 -1.159119
RJ         B -0.134841  0.390528  0.166905  0.184502
SP         C  0.807706  0.072960  0.638787  0.329646
AM         D -0.497104 -0.754070 -0.943406  0.484752
SC         E -0.116773  1.901755  0.238127  1.996652