In [1]:
import pandas as pd
import numpy as np

In [2]:
#niveis de indice
outside = ['G1', 'G1', 'G1', 'G2', 'G2', 'G2'] #primeiro nivel
inside = [1, 2, 3, 1, 2, 3] #segundo nivel
hier_index = list(zip(outside, inside)) #junta as duas listas
hier_index = pd.MultiIndex.from_tuples(hier_index) #cria index multinivel

In [3]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [4]:
inside

[1, 2, 3, 1, 2, 3]

In [5]:
nier_index = list(zip(outside, inside)) # cria uma lista de tuplas

In [6]:
nier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [7]:
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [8]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [11]:
df = pd.DataFrame(np.random.randn(6,2), index = hier_index, columns = ['A','B']) #dataframe com g1 e g2 como indecies secundarios

In [12]:
df

             A         B
G1 1 -0.831676  0.832181
   2 -1.420253  0.148869
   3  1.399321  0.147806
G2 1 -0.381889 -0.688014
   2  2.172669 -1.426539
   3  1.832365  0.473988

In [13]:
df.loc['G1'] #acessando o indice G1

          A         B
1 -0.831676  0.832181
2 -1.420253  0.148869
3  1.399321  0.147806

In [14]:
df.loc['G1'].loc[1] #acessando o indice G1 e pegando apenas a linha 1

A   -0.831676
B    0.832181
Name: 1, dtype: float64

In [16]:
df.index.names = ['Gurpo','Numero'] #expecificando nome para os indices

In [17]:
df

                     A         B
Gurpo Numero
G1    1      -0.831676  0.832181
      2      -1.420253  0.148869
      3       1.399321  0.147806
G2    1      -0.381889 -0.688014
      2       2.172669 -1.426539
      3       1.832365  0.473988

In [19]:
df.xs('G1') #prosection para selecionar o indece G1, mesma coisa que o loc, a dif eh que eh mais flexivel, permitindo escolher qual indice vc quer sem passar por indices externos para chegar nos internos

               A         B
Numero
1      -0.831676  0.832181
2      -1.420253  0.148869
3       1.399321  0.147806

In [21]:
df.xs(1, level='Numero') #pega apenas os indices 1 que sao nomeados com numero

              A         B
Gurpo
G1    -0.831676  0.832181
G2    -0.381889 -0.688014