In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [4]:
df['col2'].unique() #mantem apenas unicos valores

array([444, 555, 666])

In [5]:
np.unique(df['col2']) #mesma coisa mas com o np

array([444, 555, 666])

In [7]:
len(np.unique(df['col2'])) #tamanho do vetor de resposta

3

In [9]:
df['col2'].nunique()

3

In [10]:
df['col2'].value_counts() #une tanto o nunique quanto o unique

col2
444    2
555    1
666    1
Name: count, dtype: int64

In [11]:
df[(df['col1']>2)] #subconjunto de df

   col1  col2 col3
2     3   666  ghi
3     4   444  xyz

In [12]:
df[(df['col1']>2) & (df['col2'] == 444)] #mais um subconjunto que passa oq vc quer q ele retorne

   col1  col2 col3
3     4   444  xyz

In [13]:
df.sum()

col1              10
col2            2109
col3    abcdefghixyz
dtype: object

In [14]:
def vezes2(x): # faz * 2
    return x*2

In [15]:
df['col1'].sum()

np.int64(10)

In [16]:
df['col1'].apply(vezes2) #passa como parametro alguma funcao q criamos para fazer alguma coisa

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [17]:
df['col3'].apply(len) #tamanho da coluna 3

0    3
1    3
2    3
3    3
Name: col3, dtype: int64

In [18]:
df['col1'].apply(lambda x : x*x) #serve mais para n poluir o codigo, passando parametros lambda dentro de apply

0     1
1     4
2     9
3    16
Name: col1, dtype: int64

In [20]:
del df['col2'] #deleta coluna

In [21]:
df

   col1 col3
0     1  abc
1     2  def
2     3  ghi
3     4  xyz

In [22]:
df.columns

Index(['col1', 'col3'], dtype='object')

In [23]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [25]:
df = pd.DataFrame({'col1':[1,2,3,4],'col2':[444,555,666,444],'col3':['abc','def','ghi','xyz']})
df.head()

   col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xyz

In [26]:
df.sort_values(by='col2', inplace = True)

In [27]:
df

   col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi

In [28]:
df.dropna

<bound method DataFrame.dropna of    col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi>

In [29]:
df.isnull

<bound method DataFrame.isnull of    col1  col2 col3
0     1   444  abc
3     4   444  xyz
1     2   555  def
2     3   666  ghi>

In [30]:
df = pd.DataFrame({'col1':[1,2,3,np.nan],
                   'col2':[np.nan,555,666,444],
                   'col3':['abc','def','ghi','xyz']})
df.head()

   col1   col2 col3
0   1.0    NaN  abc
1   2.0  555.0  def
2   3.0  666.0  ghi
3   NaN  444.0  xyz